# Generated by Django 4.2.19 on 2025-08-14 06:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import web_eltekers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('peserta', 'Peserta'), ('peraga', 'Peraga'), ('instruktur', 'Instruktur'), ('pengurus_sasana', 'Pengurus Sasana'), ('pengurus_daerah', 'Pengurus Daerah')], default='peserta', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_evaluasi', models.DateField()),
                ('periode_evaluasi', models.DateField()),
                ('hasil_evaluasi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerakan',
            fields=[
                ('id_gerakan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_gerakan', models.CharField(max_length=255)),
                ('deskripsi_acuan', models.TextField()),
                ('referensi_gerakan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JadwalLatihan',
            fields=[
                ('id_jadwal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], default='Minggu', max_length=10)),
                ('jam_latihan', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=web_eltekers.models.Kabupaten)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisasiDaerah',
            fields=[
                ('id_organisasi_daerah', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id_pelatihan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pelatihan', models.CharField(max_length=255)),
                ('tanggal_pelatihan', models.DateField()),
                ('penyelenggara', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id_peserta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('tanggal_lahir_peserta', models.DateField()),
                ('kendala_terapi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sasana',
            fields=[
                ('id_sasana', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_sasana', models.CharField(max_length=255)),
                ('sejak', models.IntegerField()),
                ('alamat_sasana', models.TextField()),
                ('provinsi', models.CharField(max_length=255)),
                ('kota_kabupaten', models.CharField(max_length=255)),
                ('kecamatan', models.CharField(max_length=255)),
                ('kelurahan', models.CharField(max_length=255)),
                ('jumlah_instruktur', models.IntegerField()),
                ('jumlah_peserta', models.IntegerField()),
                ('peserta_aktif', models.IntegerField()),
                ('jumlah_latihan_per_minggu', models.IntegerField()),
                ('link_gmap', models.URLField(blank=True, max_length=500, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='sasana_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id_presensi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.jadwallatihan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.peserta')),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana')),
            ],
        ),
        migrations.AddField(
            model_name='peserta',
            name='sasana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana'),
        ),
        migrations.AddField(
            model_name='peserta',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Peraga',
            fields=[
                ('id_peraga', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_peraga', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PengurusSasana',
            fields=[
                ('id_pengurus_sasana', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pengurus_sasana', models.CharField(max_length=255)),
                ('no_telp_pengurus_sasana', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PengurusDaerah',
            fields=[
                ('id_pengurus_daerah', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pengurus_daerah', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.kecamatan')),
            ],
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.provinsi')),
            ],
        ),
        migrations.AddField(
            model_name='jadwallatihan',
            name='sasana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana'),
        ),
        migrations.CreateModel(
            name='Instruktur',
            fields=[
                ('id_instruktur', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_instruktur', models.CharField(max_length=255)),
                ('sertifikasi', models.BooleanField()),
                ('tanggal_sertifikasi', models.DateField()),
                ('file_sertifikat', models.FileField(upload_to='')),
                ('sasana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
