# Generated by Django 5.0.4 on 2025-07-09 18:01

import django.db.models.deletion
import uuid
import web_eltekers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_evaluasi", models.DateField()),
                ("periode_evaluasi", models.DateField()),
                ("hasil_evaluasi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Gerakan",
            fields=[
                (
                    "id_gerakan",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_gerakan", models.CharField(max_length=255)),
                ("deskripsi_acuan", models.TextField()),
                ("referensi_gerakan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="JadwalLatihan",
            fields=[
                (
                    "id_jadwal",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tanggal_latihan", models.DateField()),
                ("jam_latihan", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Kecamatan",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name=web_eltekers.models.Kabupaten,
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OrganisasiDaerah",
            fields=[
                (
                    "id_organisasi_daerah",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pelatihan",
            fields=[
                (
                    "id_pelatihan",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_pelatihan", models.CharField(max_length=255)),
                ("tanggal_pelatihan", models.DateField()),
                ("penyelenggara", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PengurusDaerah",
            fields=[
                (
                    "id_pengurus_daerah",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_pengurus_daerah", models.CharField(max_length=255)),
                ("jabatan", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PengurusSasana",
            fields=[
                (
                    "id_pengurus_sasana",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_pengurus_sasana", models.CharField(max_length=255)),
                ("no_telp_pengurus_sasana", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Peraga",
            fields=[
                (
                    "id_peraga",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_peraga", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Provinsi",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sasana",
            fields=[
                (
                    "id_sasana",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_sasana", models.CharField(max_length=255)),
                ("sejak", models.IntegerField()),
                ("alamat_sasana", models.TextField()),
                ("provinsi", models.CharField(max_length=255)),
                ("kota_kabupaten", models.CharField(max_length=255)),
                ("kecamatan", models.CharField(max_length=255)),
                ("kelurahan", models.CharField(max_length=255)),
                ("jumlah_instruktur", models.IntegerField()),
                ("jumlah_peserta", models.IntegerField()),
                ("peserta_aktif", models.IntegerField()),
                ("jumlah_latihan_per_minggu", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Kelurahan",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=255)),
                (
                    "provinsi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_eltekers.kecamatan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kabupaten",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=255)),
                (
                    "provinsi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_eltekers.provinsi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peserta",
            fields=[
                (
                    "id_peserta",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_peserta", models.CharField(max_length=255)),
                ("tanggal_lahir_peserta", models.DateField()),
                ("kendala_terapi", models.TextField()),
                (
                    "sasana",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_eltekers.sasana",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instruktur",
            fields=[
                (
                    "id_instruktur",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nama_instruktur", models.CharField(max_length=255)),
                ("sertifikasi", models.BooleanField()),
                ("tanggal_sertifikasi", models.DateField()),
                (
                    "file_sertifikat",
                    models.FileField(upload_to="sertifikasi_instruktur/"),
                ),
                (
                    "sasana",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_eltekers.sasana",
                    ),
                ),
            ],
        ),
    ]
