# Generated by Django 5.0.4 on 2025-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_eltekers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sasana",
            name="link_gmap",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sasana",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="sasana_profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="instruktur",
            name="file_sertifikat",
            field=models.FileField(upload_to=""),
        ),
    ]
