# Generated by Django 4.2.19 on 2025-08-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_eltekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurussasana',
            name='sasana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana'),
        ),
    ]
