# Generated by Django 4.2.23 on 2025-08-05 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_eltekers', '0002_sasana_link_gmap_sasana_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwallatihan',
            name='sasana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana'),
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id_presensi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.jadwallatihan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.peserta')),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_eltekers.sasana')),
            ],
        ),
    ]
