# Generated by Django 4.2.23 on 2025-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_eltekers', '0003_jadwallatihan_sasana_presensi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwallatihan',
            name='tanggal_latihan',
        ),
        migrations.AddField(
            model_name='jadwallatihan',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], default='Minggu', max_length=10),
        ),
    ]
